[profile.default]
src = "src"
out = "out"
libs = ["lib"]
eth-rpc-url="https://testnet-rpc.monad.xyz"
chain_id = 10143
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # store source code in the json file directly

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
